# Generated by Django 4.2.4 on 2023-08-25 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateField(default=datetime.date(1960, 1, 1)),
        ),
    ]
